fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

dummy:
    resource: "@DummyBundle/Controller/"
    type:     annotation
    prefix:   /demo

app:
    resource: "@AppBundle/Controller"
    type: annotation
